### ISSUE TITLE
与Joe主题冲突

### ISSUE THREAD

**Issue by ma3252788** [ShawnZeng1996/ContentManager#1]
启用插件之后，打开主页无法加载文章列表：

<img width="857" alt="image" src="https://github.com/ShawnZeng1996/ContentManager/assets/22229456/73e04ce1-ade5-4689-a46f-014fb847b267">

除了主页，其他地方比如类别下面的文章列表可以显示：
<img width="1064" alt="image" src="https://github.com/ShawnZeng1996/ContentManager/assets/22229456/1815c71d-fabd-4eb1-a591-9e8828ca6255">

**Comment by ma3252788** [comment]
https://github.com/HaoOuBa/Joe

这是主题链接

**Comment by ShawnZeng1996** [comment]
已修复。不过文章里面只有这个插件添加的图片的话，头图会显示不出来，需要给图片加个referrerpolicy="no-referrer"属性

**Comment by ma3252788** [comment]
> 已修复。不过文章里面只有这个插件添加的图片的话，头图会显示不出来，需要给图片加个referrerpolicy="no-referrer"属性

嗯呐，确实可以了，感谢大佬~~
