### ISSUE TITLE
能否增加电影简介呢？

### ISSUE THREAD

**Issue by ma3252788** [ShawnZeng1996/ContentManager#3]
不知道可不可以嘞~~

**Comment by ShawnZeng1996** [comment]
这个可以，当初觉得我自己没啥这方面需求就没加

**Comment by ma3252788** [comment]
> 这个可以，当初觉得我自己没啥这方面需求就没加

嗯呐，感觉加上这个之后可能更加完整，这样一个卡片就解决一个电影的介绍了~~还有图书和好物，感觉加上之后更加完整~~

期待大佬早日发布~~

**Comment by ShawnZeng1996** [comment]
电影跟图书已添加，具体更新内容看一下readme哈，好物感觉没啥必要加吧。。。而且也不知道该长啥样了，如果想要的话也可以给我个参考样式我考虑考虑~

**Comment by ShawnZeng1996** [comment]
添加观影日期跟阅读日期是为了后面做归档页面作铺垫

**Comment by ma3252788** [comment]
大佬厉害！
