### ISSUE TITLE
syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by OP404OP** [ShawnZeng1996/ContentManager#7]
emmm...数据库表的问题吗。PHP7.2
syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

**Comment by ShawnZeng1996** [comment]
完整的报错信息有吗

**Comment by OP404OP** [comment]
> 完整的报错信息有吗

😆这个就是完整的 他就显示这些就没了。

**Comment by ShawnZeng1996** [comment]
问题已复现，待我排查下

**Comment by ShawnZeng1996** [comment]
已修复，麻烦再试一下

**Comment by OP404OP** [comment]
> 已修复，麻烦再试一下

好的谢谢，我试试，另外问一句，有目前还能使用的图片自动转webp插件吗

**Comment by ShawnZeng1996** [comment]
不太清楚诶
